### ISSUE TITLE
automatic merge step for samples with replicates that differ in size

### ISSUE THREAD

**Issue by mvheetve** [nf-cmgg/preprocessing#67]
Hi there,

I've noticed that samples where there is a big difference in size between replicates (on different lanes), tend not to get merged to crams. For this reason it would be nice if there is an option to merge fastqs for rows in the samplesheet with the same sample prior to starting the pipeline. I'm testing now if its really the difference in size between the replicates that causes the issue, but it would be cool to have this feature in the future anyway. For some samples it is important to keep per lane stats, so I would suggest to make this feature optional. 

Regards
M

**Comment by mvheetve** [comment]
I can confirm that concatenating fastqs before running the pipeline does fix the issue I was experiencing. So a flag for a pre-run merge step would be amazing. 

Regards
M

**Comment by matthdsm** [comment]
Fixed in #115 by fixing the groupTuple flow, no more concatenation needed
