### ISSUE TITLE
can't find genome_base suddenly

### ISSUE THREAD

**Issue by mvheetve** [nf-cmgg/preprocessing#93]
### Description of the bug

Hej M,

I tried to use preprocess on a WGS run. 

This seems strange to me. I went back to the logs of a recent (few weeks) WES run and there I had a very similar command, without this issue. I've tried including `--fasta`, `--fai` and `--dict`, but looking at `genomes.config` I see a lot more relies on `genomes_base`. In the end I just made a fork and adapted the config, but I'd like to know what happened. The problem lies with `Hsapiens/GRCh38.p14`, which is not a directory in `kyukon/data/gent/shared/000/gvo00082/genomes`. In the config of the previous WES run, there is also mentioning of `Hsapiens/GRCh38.p14`, so now I'm wondering if the name of the GRCh38 directory recently changed in `kyukon/data/gent/shared/000/gvo00082/genomes`. 

The fork I made is currently running successfully. Here's a [link](https://github.com/mvheetve/preprocessing/tree/main). I've included the logs of the failed run. 

Would be mighty fine if we could clear this up. I you need any extra info or files, let me know. 

### Command used and terminal output

```console
genomes_base=/kyukon/data/gent/shared/000/gvo00082/genomes

/kyukon/data/gent/430/vsc43079/miniconda3/bin/nextflow \
	-log ${OUTDIR}/.nextflow.log \
	run nf-cmgg/preprocessing \
		-r v1.2.0 \
		-latest \
		-resume \
		-work-dir ${WORKDIR} \
		-profile vsc_ugent,${SLURM_CLUSTERS},WGS \
		--fastq ${samplesheet} \
		--outdir ${OUTDIR} \
		--genomes_base ${genomes_base}

N E X T F L O W   ~  version 24.04.3

Pulling CenterForMedicalGeneticsGhent/nf-cmgg-preprocessing ...
WARN: It appears you have never run this project before -- Option `-resume` is ignored
Launching `https://github.com/CenterForMedicalGeneticsGhent/nf-cmgg-preprocessing` [maniac_morse] DSL2 - revision: 660d3d6ddd [v1.2.0]

WARN: The following invalid input values have been detected:

* --input: /kyukon/data/gent/vo/000/gvo00082/research/LabDeBaere/srWGS/240423_A00785_0997_BH5G2YDSXC/NVQ_997_preprocess_samplesheet.csv


ERROR ~ ERROR: Validation of pipeline parameters failed!

 -- Check '/kyukon/data/gent/vo/000/gvo00082/research/LabDeBaere/srWGS/240423_A00785_0997_BH5G2YDSXC/preprocess/.nextflow.log' file for details
(base) [vsc43079@gligar07 preprocess_nodumpchannel]$ cat NVQ_997_preprocess.err 
Nextflow 23.10.4 is available - Please consider updating your version to it
Using the '-profile vsc_ugent,<cluster>' is deprecated in favor of '-profile vsc_ugent'. The config will now automatically determine the currently used cluster.
The following invalid input values have been detected:

* --fasta: the file or directory '/kyukon/data/gent/shared/000/gvo00082/genomes/Hsapiens/GRCh38.p14/seq/GCA_000001405.15_GRCh38_full_plus_hs38d1_analysis_set.fna' does not exist.

 -- Check script '/kyukon/home/gent/430/vsc43079/.nextflow/assets/CenterForMedicalGeneticsGhent/nf-cmgg-preprocessing/main.nf' at line: 48 or see '/kyukon/data/gent/vo/000/gvo00082/research/LabDeBaere/srWGS/240423_A00785_0997_BH5G2YDSXC/preprocess/.nextflow.log' file for more details
```

### Relevant files

[nextflow.log](https://github.com/user-attachments/files/16454155/nextflow.log)

### System information

HPC shinx

**Comment by matthdsm** [comment]
Path for genomes_base was changed on HPC and UGent iGenomes. Config changes are present in v2.0
